default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: restauranta_app_development

test:
  <<: *default
  database: restauranta_app_test

production:
  <<: *default
  database: restauranta_app_production
  username: restauranta_app
  password: <%= ENV['RESTAURANTA_APP_DATABASE_PASSWORD'] %>
